//
//  NewsInterfaces.swift
//  TiTech
//
//  Created by Apple on 10/7/24.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol NewsWireframeInterface: WireframeInterface {
    func showLoading()
    func hideLoading()
    func openNewDetail(url: String)
}

protocol NewsViewInterface: ViewInterface {
    func reloadCategoryList()
    func reloadTableViewContent()
}

protocol NewsPresenterInterface: PresenterInterface {
    var categoryList: [NewCategory] { get set }
    var listNews: [NewsItem] { get set }
    
    func sendGetCategoryRequest()
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int 
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath)
    
    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int
    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell
    func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) 
}

protocol NewsInteractorInterface: InteractorInterface {
    func handleGetCategory(completion: @escaping (CategoryResponse?) -> Void)
    func handleGetListNews(categoryId: Int, completion: @escaping ([NewsItem]?) -> Void)
}

protocol NewsFormatterInterface: FormatterInterface {
    
}

