//
//  NewsWireframe.swift
//  TiTech
//
//  Created by Apple on 10/7/24.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class NewsWireframe: BaseWireframe<NewsViewController> {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard(name: "News", bundle: nil)
    private let newService = NewService()

    // MARK: - Module setup -

    init() {
        let moduleViewController = storyboard.instantiateViewController(ofType: NewsViewController.self)
        super.init(viewController: moduleViewController)

        let formatter = NewsFormatter()
        let interactor = NewsInteractor(service: newService)
        let presenter = NewsPresenter(view: moduleViewController, formatter: formatter, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
        
        moduleViewController.title = "Tin tức"
    }

}

// MARK: - Extensions -

extension NewsWireframe: NewsWireframeInterface {
    func showLoading() {
        self.viewController.showProgressHud()
    }
    
    func hideLoading() {
        self.viewController.hideProgressHud()
    }
    
    func openNewDetail(url: String) {
        let viewController = NewDetailWireframe(addressURL: url)
        self.viewController.navigationController?.pushWireframe(viewController)
    }
}
