//
//  NewsFormatter.swift
//  TiTech
//
//  Created by Apple on 10/7/24.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class NewsFormatter {
}

// MARK: - Extensions -

extension NewsFormatter: NewsFormatterInterface {
    
}
