//
//  NewsInterfaces.swift
//  TiTech
//
//  Created by Apple on 10/7/24.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol NewsWireframeInterface: WireframeInterface {
    func showLoading()
    func hideLoading()
}

protocol NewsViewInterface: ViewInterface {
    func reloadCategoryList()
    func reloadTableViewContent()
}

protocol NewsPresenterInterface: PresenterInterface {
    var categoryList: [NewCategory] { get set }
    var listNews: [NewsItem] { get set }
    
    func sendGetCategoryRequest()
    func sendGetListNews(categoryId: Int)
}

protocol NewsFormatterInterface: FormatterInterface {
    
}

protocol NewsInteractorInterface: InteractorInterface {
    func handleGetCategory(completion: @escaping (CategoryResponse?) -> Void)
    func handleGetListNews(categoryId: Int, completion: @escaping ([NewsItem]?) -> Void)
}
