//
//  ChatAIInteractor.swift
//  TiTech
//
//  Created by Apple on 9/7/24.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class ChatAIInteractor { 
    private let chatService: ChatServiceProtocols
    
    init(chatService: ChatServiceProtocols) {
        self.chatService = chatService
    }
}

// MARK: - Extensions -

extension ChatAIInteractor: ChatAIInteractorInterface {
    func handleChatRequest(message: String, completion: @escaping (String?) -> Void) {
        self.chatService.sendMessage(message: message) { result in
            switch result {
            case .success(let response):
                if let content = response?.content  {
                    completion(content)
                } else {
                    completion(nil)
                }
            case .failure:
                completion(nil)
            }
        }
    }
}
