//
//  ChatAIInterfaces.swift
//  TiTech
//
//  Created by Apple on 9/7/24.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol ChatAIWireframeInterface: WireframeInterface {
    
}

protocol ChatAIViewInterface: ViewInterface {
    func didHandleChat(result: String)
}

protocol ChatAIPresenterInterface: PresenterInterface {
    func sendChatRequest(with message: String)
}

protocol ChatAIInteractorInterface: InteractorInterface {
    func handleChatRequest(message: String, completion: @escaping (String?) -> Void)
}
