//
//  NewDetailInterfaces.swift
//  TiTech
//
//  Created by Apple on 11/7/24.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol NewDetailWireframeInterface: WireframeInterface {
}

protocol NewDetailViewInterface: ViewInterface {
    
}

protocol NewDetailPresenterInterface: PresenterInterface {
    var addressURL: String { get set}
}
