//
//  NewDetailPresenter.swift
//  TiTech
//
//  Created by Apple on 11/7/24.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class NewDetailPresenter {
    
    // MARK: - Private properties -

    private unowned let view: NewDetailViewInterface
    private let wireframe: NewDetailWireframeInterface

    // MARK: - Lifecycle -
    var addressURL: String = ""

    init(view: NewDetailViewInterface, wireframe: NewDetailWireframeInterface) {
        self.view = view
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension NewDetailPresenter: NewDetailPresenterInterface {
}
