//
//  NewDetailWireframe.swift
//  TiTech
//
//  Created by Apple on 11/7/24.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class NewDetailWireframe: BaseWireframe<NewDetailViewController> {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard(name: "NewDetail", bundle: nil)
    var addressURL: String

    // MARK: - Module setup -

    init(addressURL: String) {
        self.addressURL = addressURL
        let moduleViewController = storyboard.instantiateViewController(ofType: NewDetailViewController.self)
        super.init(viewController: moduleViewController)

        let presenter = NewDetailPresenter(view: moduleViewController, wireframe: self)
        presenter.addressURL = self.addressURL
        moduleViewController.presenter = presenter
        
        moduleViewController.title = "Chi tiết"
    }

}

// MARK: - Extensions -

extension NewDetailWireframe: NewDetailWireframeInterface {
}
