//
//  LoginViewController.swift
//  TiTech
//
//  Created by Apple on 9/7/24.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class LoginViewController: BaseViewcontroller {

    // MARK: - Public properties -
    @IBOutlet weak var emailView: VFTTextField!
    @IBOutlet weak var passwordView: VFTTextField!
    @IBOutlet weak var passwordSecureView: UIButton!

    var presenter: LoginPresenterInterface!
    private var isSecure = true

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        self.emailView.textField.text = "testmail1@gmail.com"
        self.passwordView.textField.text = "123456"
    }
    
    @IBAction func onLoginTap(_ sender: UIButton) {
        if self.emailView.textField.text != "" && self.passwordView.textField.text != "" {
            self.presenter.sendLoginRequest(username: self.emailView.textField.text ?? "",
                                            password: self.passwordView.textField.text ?? "")
        }
    }
    
    @IBAction func onSecureTap(_ sender: UIButton) {
        self.isSecure.toggle()
        self.passwordView.textField.isSecureTextEntry = self.isSecure
        self.passwordSecureView.setImage(isSecure ? UIImage(named: "ic_eye") : UIImage(named: "ic_eye_closed"), for: .normal)
    }
    
    @IBAction func onLoginBiometric(_ sender: UIButton) {
        let bioAuth = BiometricAuthenticator()
        if bioAuth.isTouchIdEnabledOnDevice() || bioAuth.isFaceIdEnabledOnDevice() {
            bioAuth.authenticateWithBiometrics {
                DispatchQueue.main.async {
                    if self.emailView.textField.text != "" && self.passwordView.textField.text != "" {
                        self.presenter.sendLoginRequest(username: self.emailView.textField.text ?? "",
                                                        password: self.passwordView.textField.text ?? "")
                    }
                }
            } failureBlock: { error in
                self.presenter.showAlert(error?.localizedDescription ?? "", actionTitle: "Đóng", action: nil)
            }
        } else {
            self.presenter.showAlert("Thiết bị không hỗ trợ hoặc bạn cần thiết lập sinh trắc học trước khi sử dụng tính năng này", actionTitle: "Đóng", action: nil)
        }
    }
}

// MARK: - Extensions -
extension LoginViewController: LoginViewInterface { }
