//
//  LoginWireframe.swift
//  TiTech
//
//  Created by Apple on 9/7/24.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class LoginWireframe: BaseWireframe<LoginViewController> {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard(name: "Login", bundle: nil)
    private var loginSerivce: LoginServiceProtocols
    private let loadingView = LoadingView()

    // MARK: - Module setup -

    init() {
        // api services
        self.loginSerivce = LoginService()
        
        let moduleViewController = storyboard.instantiateViewController(ofType: LoginViewController.self)
        super.init(viewController: moduleViewController)

        let presenter = LoginPresenter(view: moduleViewController, wireframe: self)
        moduleViewController.presenter = presenter
    }
}

// MARK: - Extensions -

extension LoginWireframe: LoginWireframeInterface {
    func hanleLoginTask(userInput: String, passwordInput: String) {
        loadingView.show(on: self.viewController.view)
        self.loginSerivce.login(username: userInput,
                                password: passwordInput) {[weak self] isSuccess in
            guard let strongSelf = self else { return }
            strongSelf.loadingView.hide()
            if isSuccess {
                strongSelf.navigationController?.pushWireframe(NewsWireframe(), animated: true)
            }
        }
    }
    
    func hanleShowAlert(alertVC: UIAlertController) {
        self.viewController.present(alertVC, animated: true)
    }
}
